version: '3'

services:
  anonymousoverflow:
    container_name: 'app'
    build:
      context: .
      network: 'host'
    environment:
      - APP_URL=https://domain.com
      - JWT_SIGNING_SECRET=secret
    ports:
      - '80:8080'
    restart: 'always'